version: '3.8'

services:
  bot:
    build: .
    container_name: discord_bot
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - lavalink

  lavalink:
    image: fredboat/lavalink:master
    container_name: lavalink
    restart: always
    ports:
      - "2333:2333"
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
